#Config Version
config-version: 'v5'
#Enable or disable the update checker
update-checker-enabled: true
#Password For Disabling and enabling
password: 'Th3B3stPassw0rdinth3W0r1d'
#Protocol Settings
protocolsettings:
#Protocol name
 protocol-name: 'Network'
#MOTD
 motd: 
  1: '&6Network is &5now open!'
  2: '&3Come To &aPlay'
#Max Players
 max-players: 100
#Allowed Protocols , check out this link for protocol version numbers wiki.vg/Protocol_version_numbers
 allowed-protocols:
  - 340
  - 393
  - 401
  - 477
  - 485
  - 490
#Blocked Message
 blocked-message: 'You are not allowed to use this minecraft version'
#Default Protocol , check out this link for protocol version numbers wiki.vg/Protocol_version_numbers
 default-allowed-protocol: 340
#Hover Message
 hover-message: 
  - '&6New Server is here!'
  - '&3COMEEEE'
#Prefixs
prefixs:
 #Prefix of Plugin
 plugin: '&7[&3CustomProt&6ocolSettings&7]'
 #Prefix of the Ping Command
 ping: '&7[&3Pi&6ng&7]'
#Maintenance Settings
maintenancesettings:
 enabled: false
 motd: 
  1: 'New Update on maintenance'
  2: 'Please Wait'
 hover-message: 
  - 'Maintenance'
 blocked-message: 'We are currently on maintenance , There are %online% staff(s) online in maintenance'
#Allowed Players to join while in maintenance
 allowed-players:
 - 'owner'
 - 'staff1'
 - 'staff2'
#for help check out https://github.com/Begad666/cps/wiki/Help