#Config Version
config-version: 'v8.0.0'
#Enable or disable the update checker
update-checker-enabled: true
#Set the current language
language: 'en'

#Info about your network
network-info:
  #The name of the network used in %net-name% placeholder
  name: 'Network'
  #The server version when there is a not supported client
  server-version: "Network 1.16.x"
  #The server version when maintenance mode is enabled
  maintenance-version: "Maintenance"
  #Max Players, used for player count and max player checking, set to 0 for 1 slot added when a player pings
  max-players: 100

#Settings for the server
settings:
  #Should the plugin block users not allowed by the list below?
  allow-all-versions: false
  #Allowed protocols versions to join, to know more about protocols check this out https://wiki.vg/Protocol_version_numbers
  allowed-protocols:
    - 735
    - 736
    - 751
  #Protocol sent when the client doesn't match any of the above (Better to be the proxy server protocol)
  default-protocol: 751
  #Is maintenance enabled?
  maintenance-enabled: false
  #Should the plugin enable /ping command?
  ping-enabled: true
  #How should the plugin check if a player can join while in maintenance or perform super admin commands
  #Available options are: PERM for permission based (cps.bypass), CONFIG_ALLOWED_PLAYERS for allowed-players config section (go down), default is PERM
  #PERM Based can only be tested AFTER the player has logged in
  #CONFIG_ALLOWED_PLAYERS Based can be tested BEFORE and AFTER the player has logged in (More info down at allowed-players section)
  check-type: PERM

#MOTDs
motds:
  #Default MOTD while maintenance isn't enabled
  default-motd:
    1: '&6Network is &5now open!'
    2: '&3Come To &aPlay'
  #Opposite of above
  maintenance-motd:
    1: 'New Update on maintenance'
    2: 'Please Wait'

#Hover messages
hover-messages:
  #Enable hover messages
  enable: true
  #Display player names instead of using the messages below
  show-players: false
  #Message shown when hovering the mouse over the player count while maintenance isn't enabled
  default-hover-message:
    - 'Network'
  #Opposite of the above
  maintenance-hover-message:
    - 'Maintenance'

#Prefix of Plugin
plugin-prefix: '&7[&3CustomProt&6ocolSettings&7]'

#Messages
messages:
  #Message when the client doesn't match the allowed protocols above
  not-supported-client-message: 'You are not allowed to use this minecraft version'
  #Message when the client doesn't match the allowed players when there is a maintenance
  maintenance-message: 'We are currently on maintenance, there are %online% staff(s) online in maintenance'
  #Message when the server is full
  full-message: 'The server is full, try again later'

#Allowed Players to (join while players full or maintenance or use super admin commands), UUIDs are supported with online-mode: true servers and player names are supported with online-mode: false servers
#The plugin uses your server online mode setting to determine what type to use
#Also, if online mode is true then the plugin will check after the player has logged in using UUID, otherwise before (but will use username)
allowed-players:
  - 'owner'
  - 'staff1'
  - 'staff2'
#Backup settings
backup:
  #Where to place the backup (relative to the plugin data directory)
  #For example, if you have installed bungeecord at /servers/proxy or C:\server\proxy
  #if you want to store backups at /servers/proxy/backups/cps
  #then you will need to set this to "../../backups/cps"
  folder: 'backup'
  #how should the plugin name the file, the plugin will append .yml to the file automatically
  #Placeholders:
  # {time} - replaces it with current time e.g. 11_00AM or 3_02PM (here _ means :)
  # {date} - replaces it with current date e.g. 02_15_2020 (also here _ means /)
  # those placeholders will use the server time zone
  name: 'backup_{time}'
#MultiProxy Support
multiproxy:
  #Enable MultiProxy Support
  enable: false
  #ID of the Group
  groupid: '1'
  #Should the plugin auto replace unicode characters (go to bottom of the file)
  autoreplace: true
  #MultiProxy backup settings
  backup:
    #Should the plugin backup the config file when a pull happens
    enable: true
    #Should the plugin stop pulling when an error happens when backing up
    stoponerror: true

#The connection settings for the database (Currently MySQL/MariaDB is Supported)
connectionsettings:
  #Where the database are hosted
  host: 'localhost'
  #The Port (usually 3306)
  port: 3306
  #The Database Name
  database: 'minecraft'
  #The User of the Database
  user: 'root'
  #The User Password
  password: ''

#Replace strings
#This section used when a unicode characters is found (Won't get added into the database if using multiproxy)
replace:
  u0026: '&'
  u0025: '%'
  u0024: '$'
  u0023: '#'
  u0022: '"'
  u0021: '!'
  u0027: ''''
  u002F: '/'
  u002A: '*'
#Done, go type /cps reload